language: python

before_script:
  - npm install -g aglio

script:
  - aglio -i docs/mqtt-manager.apib -o docs/apis.html

deploy:
  local_dir: docs
  target_branch: gh-pages
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
